### ISSUE TITLE
Simplify class structure

### ISSUE THREAD

**Issue by zeelot** [kohana-minion/tasks-migrations#11]
I'm trying to read through the classes to see what they do and it just seems like there are some unnecessary ones... maybe we could use this ticket to discuss the structure. The first class I would like to get rid of is the `Minion_Migration_Util` class. From the looks of it, everything in there could be placed in the model.

**Comment by bobeagan** [comment]
+1 for killing the Util class

**Comment by zeelot** [comment]
I would also like to rename the tasks in here.`db:generate` makes little sense. This module is about migrations so we should stick to namespacing the tasks under `migrations:*. Here are my choices:

```
migrations:generate
migrations:run
migrations:status
```

Then I want to change `--migrate-up`, `--migrate-down`, and `--migrate-to` to simply say `--up`, `--down`, and `--to`. We already know we are migrating, there is no need to repeat that in every option.

I'd like some feedback because I think these changes will make the module ready for its first release.

**Comment by bobeagan** [comment]
Might also be good for you to review and provide feedback on kohana-minion/core#31

**Comment by zeelot** [comment]
Going with  `migrations:new` instead of generate because it is shorter and clearer. If someone had some scaffolding modules, they might expect `generate` to create migrations based on models or something of that sort.

**Comment by zeelot** [comment]
The rest of the files seem ok, closing.
