### ISSUE TITLE
Minion_Migration_Util::get_class_from_migration() returning incorrect class name when location is empty

### ISSUE THREAD

**Issue by BRMatt** [kohana-minion/tasks-migrations#2]
Ported from kohana-minion/core#4
## Ticket

If I run the following command
    php public/index.php --uri=minion/db:generate --location=application/migrations/ --description="Add one-to-many relationship"

the migration class name that results is
    Migration_20110107011624

When I try to run the migrations this exception is thrown
    ErrorException [ 1 ]: Class 'Migration_._20110107001421' not found ~ MODPATH/minion/classes/minion/migration/manager.php [ 185 ]
## Comments

BRMatt January 21, 2011 
I'm tempted to reject this, in my opinion migrations in the application should be placed in a folder structure such as "application/migrations/app" or "application/migrations/application".

ahutchings January 23, 2011
That does make sense. Perhaps this should be a documentation issue instead, or the db:generate task could reject invalid locations, or both.

**Comment by bobeagan** [comment]
Matt, can you provide any more reasoning as to why you feel people shouldn't be able to place migration files in the root migrations directory?

**Comment by BRMatt** [comment]
Well for a start how would you refer to them using the `--group` notation?

**Comment by bobeagan** [comment]
Well `--group` is optional if you just run `db:migrate`.  People could still try to generate migration files in the migrations base directory.

**Comment by BRMatt** [comment]
But if you wanted to migrate those migrations only then there's no way to refer to them without adding a new switch, which is just messy.  I suppose the best solution is to just warn them not to do it if they try

**Comment by bobeagan** [comment]
Yeah, definitely seems like some check in generate would be useful to help protect people from making that mistake.

**Comment by zeelot** [comment]
This seems solved by #22. The --group now refers to the folder name starting in `migrations/` and is required, so making migrations at the root of the directory is impossible. I will test that pull request and make sure it is the case before merging.
