### ISSUE TITLE
Location aliases and preventing autoload errors

### ISSUE THREAD

**Issue by BRMatt** [kohana-minion/tasks-migrations#3]
Porting over from kohana-minion/core#23
## Ticket

In order to avoid any mistakes, at which the structure breaks down the names of classes, I decided to use something called aliases. I can not for a long time to explain what I mean and I can just invite you to download my fork of your framework and insight into:

```
php --uri=minion --locations
```

Accordingly, this functional is used in the generation of ORM models. For example:

```
php --uri=minion/model:generate --name=test --location=application
```

**Comment by bobeagan** [comment]
Close this issue.  This guy is doing his own thing at https://github.com/Leemo/kohana-assist
