### ISSUE TITLE
Init migrations table task

### ISSUE THREAD

**Issue by evanpurkhiser** [kohana-minion/tasks-migrations#32]
I actually haven't used this module yet, in fact I have never used database migrations before, but I have been doing some reading and am looking forward to using it.

Looking through this module it looks like there is a little bit of work that has to be done before we can actually run the migrations on a cold database (Empty database). what about something like this?

`migrations:init` - This would setup the `minion_migrations` SQL table that this module requires to keep track of applied migrations. This is more or less just something used to automate the initial deployment of an application. Once the table is setup, then the migrations can be run to bring the database up to date.

Again, I haven't actually used this module just yet, so I was just curious if this would be something that would fit in the module?

**Comment by zeelot** [comment]
From what I recall, the initial table is created automatically on the first run

**Comment by evanpurkhiser** [comment]
You'r correct. [It does](https://github.com/kohana-minion/tasks-migrations/blob/3.1/develop/classes/model/minion/migration.php#L167)

I didn't look at the code hard enough =)
