### ISSUE TITLE
tests do not setup and teardown testing tables

### ISSUE THREAD

**Issue by bobeagan** [kohana-minion/tasks-migrations#5]
Need the unittests to create and destroy the test tables that they use on the database.  Right now the tests are failing because the tables don't exist and I shouldn't have to manually add them in order for the tests to work.

**Comment by BRMatt** [comment]
They are created if you run the migrations in the minion location, though perhaps this should be moved to the setupclass/teardownclass methods...

**Comment by bobeagan** [comment]
I believe they should be handled by the setup and teardown.  When our CI system tries to automatically run the unit tests, I shouldn't have to add an extra task that runs first to execute the minion migration task just for this module.

**Comment by BRMatt** [comment]
Changing tests to auto-create and auto-teardown the testing table closed by 17b36782e1cae153804d41bbd60f05e99847cdff
