### ISSUE TITLE
Locations don't appear to work.

### ISSUE THREAD

**Issue by ThePixelDeveloper** [kohana-minion/tasks-migrations#6]
I'm having trouble getting the locations feature to work properly.

I only want to run migrations under a directory called `nolimits`. I've tried.
- `./minion db:migrate --dry-run --versions=nolimits:TRUE`
- `./minion db:migrate --dry-run --locations=nolimits --versions=TRUE`

but both of those commands are outputting:

<pre>
##########################
# Begin Location: minion #
##########################

# Begin 20110110093709

CREATE TABLE `test_minion_migrations` (
  `timestamp` varchar(14) NOT NULL,
  `description` varchar(100) NOT NULL,
  `location` varchar(100) NOT NULL,
  `applied` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`timestamp`,`location`),
  UNIQUE KEY `MIGRATION_ID` (`timestamp`,`description`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;;

# End 20110110093709

########################
# End Location: minion #
########################
</pre>

Am I missing something or is the feature broken?

**Comment by ThePixelDeveloper** [comment]
Ok.

The problem was I had not created the `nolimits` directory, maybe it'd be nice to show a warning instead of migrations which don't apply.

The next problem was only 

```
./minion db:migrate --dry-run --locations=nolimits --versions=TRUE
```

displayed the correct migrations (with the directory created), where as:

```
./minion db:migrate --dry-run --versions=nolimits:TRUE
```

would still give me the incorrect output.

**Comment by BRMatt** [comment]
Now throws an exception if a group doesn't exist, just need to prettify the output.

**Comment by bobeagan** [comment]
Is this ticket still relevant?  Can you reproduce this problem using the new option configuration?

**Comment by BRMatt** [comment]
Going to close this, please reopen if problem exists / resurfaces
