### ISSUE TITLE
Remove applied and description from the migrations table

### ISSUE THREAD

**Issue by ThePixelDeveloper** [kohana-minion/tasks-migrations#8]
Consider the migration applied if has been entered into the minion_migrations table. This should hopefully clean up the internals a bit.

What is the description field used for? You could probably live with just the timestamp and the group.

**Comment by BRMatt** [comment]
Description field is used for working out the filename of the migration.  There are both applied & unapplied migrations in the table to make it easier to work out which ones need applying when the user specifies a target.

**Comment by ThePixelDeveloper** [comment]
Ok on the description field. As for the applied field, still doesn't make sense to me.

Consider everything in the table already applied. If you need to move down a few migrations then it's easy to work out. Order the table by the timestamp column and go back however far you need (if it's in the -n syntax). Same concept if you're going down to a specific point, keep going back until you get a match of the timestamp/description.

Same thing applies for when you're going up, except instead of checking the database you're now checking the file system. I think it'd make your life easier.

Thanks for taking a look.

**Comment by zeelot** [comment]
I would rather keep the applied column. When migrations fail I like to be able to look at the table and be able to tell where it failed right away instead of having to look at the table AND the filesystem. It doesn't add too much complexity so I'm not sure of the benefit of removing this.

**Comment by ThePixelDeveloper** [comment]
Zeelot, that can be solved by looking at the log output.

Say if you ran a migration and it failed, then it'd be logged to the STDOUT or whatever you have attached to the log_writer.
